# Generated by Django 4.2.7 on 2023-11-07 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='students'),
        ),
    ]
